environment:
  # Version 4.2.3 has a prebuilt binary available. TODO: Build Windows binary
  # in this project.
  ZMQ_VERSION: 4.2.3
  GH_TOKEN:
    secure: 6V8UzhSBNiXKcwNF1cTFaqTZaX/YVUWutdbluQVdXPlUn1u9G+cd1XTgyZQDmD+4
  matrix:
  - node_js: 9.7

platform:
- x64
- x86

init:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

build: off

on_finish:
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
- ps: Install-Product node $env:node_js $env:platform
- appveyor-retry call sh script/ci/install.sh

test_script:
- appveyor-retry call yarn test

deploy_script:
- IF "%appveyor_repo_tag%"=="true" sh script/ci/release.sh
